### DISCUSSION TITLE
Adicionando Font Family no flutter

### DISCUSSION THREAD

**Discussion by filipecancio** [filipecancio/melhores-marcas#25] [Flutter]
Vamos fazer download da fonte [Abel](https://fonts.google.com/specimen/Abel?query=Abel)
Em seguida, basta descompactar o arquivo zip, criar uma pasta chamada `fonts` no diretório raiz (no nosso projeto, em `mmflutter`) e colar o arquivo `.tff`:
![image](https://user-images.githubusercontent.com/13178261/163728535-c2ef54d1-8457-4be4-b20e-72e1c2113bd3.png)
em seguida, coloque em no arquivo `pubspec.yml`:
```yml
flutter: #você não precisa colocar essa linha, é apenas uma referência de identação
  fonts:
    - family: Abel
      fonts:
        - asset: fonts/Abel-Regular.ttf
```
Depois basta acrescentar o font familiy no widget desejado:
```Dart
Text(
  "Melhores Marcas",
  style: TextStyle(fontFamily: 'Abel'),
),
```
